# Generated by Django 4.2 on 2023-05-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('BIZUM', 'Bizum')], default='Cash', max_length=9)),
                ('instructions', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
