# Generated by Django 4.2 on 2023-05-22 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_location', models.CharField()),
                ('return_date', models.CharField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('BIZUM', 'Bizum')], default='Cash', max_length=9)),
                ('order_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending_payment'), ('PAYMENT_RECEIVED', 'Payment_received'), ('CANCELLED', 'Cancelled')], default='Pending_payment', max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.OrderProduct', to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
