# Generated by Django 4.2 on 2023-05-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_name'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_return_location', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pickup_location', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_date',
            field=models.DateField(),
        ),
    ]
