# Generated by Django 4.2 on 2023-05-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
        ('orders', '0002_order_return_location_alter_order_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_methods.paymentmethod'),
        ),
    ]
