# Generated by Django 4.2 on 2023-05-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_accessories_id_and_more'),
    ]

    operations = [
    ]
